version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: flaskdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
